# Generated by Django 3.2.6 on 2023-04-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamlead',
            name='image',
            field=models.FileField(default=0, upload_to='media/leads/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='media/event_images/'),
        ),
    ]
