# Generated by Django 3.2.6 on 2023-04-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20230414_0519'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='about_images/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(upload_to='event_images/'),
        ),
        migrations.AlterField(
            model_name='teamlead',
            name='image',
            field=models.FileField(upload_to='leads/'),
        ),
    ]
