# Generated by Django 3.2.6 on 2023-04-14 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20230414_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headquarter', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('copyright', models.CharField(max_length=255)),
                ('designer', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('careers_link', models.URLField()),
                ('investor_link', models.URLField()),
                ('terms_conditions_link', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
