# Generated by Django 3.2.6 on 2023-04-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20230414_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamlead',
            name='social_links',
            field=models.TextField(),
        ),
    ]
